'use strict';
angular.module('manage').config(['$stateProvider',
	function($stateProvider) {
		$stateProvider
		.state('manage',{
			url:'/manage',		
			abstract : true,	
			templateUrl:'app/modules/manage/views/manage-side-nav.view.html'			
		})
		.state('manage.home',{
			url:'',
			templateUrl:'app/modules/manage/views/manage.view.html'				
		})
		//Accounts
		.state('manage.funtownAccount',{
			url:'/funtownAccount',
			templateUrl:'app/modules/account/views/funtown-account.view.html'
		})
		.state('manage.paynowAccount',{
			url:'/paynowAccount',
			templateUrl:'app/modules/account/views/paynow-account.view.html'
		})
		//Buying
		.state('manage.orders',{
			url:'/orders',
			templateUrl:'app/modules/buying/views/orders.view.html'
		})
		.state('manage.watchlist',{
			url:'/watchlist',
			templateUrl:'app/modules/buying/views/watchlist.view.html'
		})
		.state('manage.shippingAddress',{
			url:'/shippingAddress',
			templateUrl:'app/modules/buying/views/shippingAddress.view.html'
		})
		//Selling
		.state('manage.products',{
			url:'/products',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html'
		})
		.state('manage.products.ACTIVE',{
			url:'/selling',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html',
			resolve:{
				products: function(ProductsViewService){
					return ProductsViewService.getProductsOfStatus("ACTIVE");
				}
			}
		})
		.state('manage.products.SOLD',{
			url:'/sold',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html'
		})
		.state('manage.products.OUT_OF_STOCK',{
			url:'/outOfStock',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html'
		})
		.state('manage.products.DE_ACTIVE',{
			url:'/deactive',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html'
		})
		.state('manage.products.IN_DRAFT',{
			url:'/indraft',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html'
		})
		//addProduct
		.state('manage.addProduct',{
			url:'/addProduct',
			controller:'AddProduct',
			abstract : true,
			templateUrl:'app/modules/selling/views/products-add.view.html',
			resolve:{
				AttributeService: function(AttributeService){
					return AttributeService;
				}
			}
		})
		.state('manage.addProduct.step1',{	
			url:'/addProduct/step1',
			controller:'AddProductStep1',		
			templateUrl:'app/modules/selling/views/products-add-step1.view.html'
		})
		.state('manage.addProduct.step2',{
			url:'/addProduct/step2',
			controller:'AddProductStep2',	
			templateUrl:'app/modules/selling/views/products-add-step2.view.html'
		})
		.state('manage.addProduct.step3',{
			url:'/addProduct/step3',
			controller:'AddProductStep3',
			templateUrl:'app/modules/selling/views/products-add-step3.view.html'
		})
		.state('manage.addProduct.step4',{
			url:'/addProduct/step4',
			controller:'AddProductStep4',
			templateUrl:'app/modules/selling/views/products-add-step4.view.html'
		})
		.state('manage.addProduct.step5',{
			url:'/addProduct/step5',
			controller:'AddProductStep5',
			templateUrl:'app/modules/selling/views/products-add-step5.view.html'
		})
		.state('manage.addProduct.step6',{
			url:'/addProduct/step6',
			controller:'AddProductStep6',
			templateUrl:'app/modules/selling/views/products-add-step6.view.html'
		})
	}
])