angular.module('manage').config(['$stateProvider',
	function($stateProvider) {
		$stateProvider
		.state('manage',{
			url:'/manage',		
			abstract : true,	
			templateUrl:'app/modules/manage/views/manage-side-nav.view.html'			
		})
		.state('manage.home',{
			url:'',
			templateUrl:'app/modules/manage/views/manage.view.html'				
		})
		//Accounts
		.state('manage.funtownAccount',{
			url:'/funtownAccount',
			templateUrl:'app/modules/account/views/funtown-account.view.html'
		})
		.state('manage.paynowAccount',{
			url:'/paynowAccount',
			templateUrl:'app/modules/account/views/paynow-account.view.html'
		})
		//Buying
		.state('manage.orders',{
			url:'/orders',
			templateUrl:'app/modules/buying/views/orders.view.html'
		})
		.state('manage.watchlist',{
			url:'/watchlist',
			templateUrl:'app/modules/buying/views/orders.view.html'
		})
		.state('manage.shippingAddress',{
			url:'/shippingAddress',
			templateUrl:'app/modules/buying/views/shippingAddress.view.html'
		})
		//Selling
		.state('manage.products',{
			url:'/products',
			controller:'ProductsView',
			templateUrl:'app/modules/selling/views/products-home.view.html'
		})
		.state('manage.products.selling',{
			url:'/selling',
			templateUrl:'app/modules/selling/views/products.view.html'
		})
		.state('manage.products.sold',{
			url:'/sold',
			templateUrl:'app/modules/selling/views/products.view.html'
		})
		.state('manage.products.outOfStock',{
			url:'/outOfStock',
			templateUrl:'app/modules/selling/views/products.view.html'
		})
		.state('manage.products.deactive',{
			url:'/deactive',
			templateUrl:'app/modules/selling/views/products.view.html'
		})
		.state('manage.products.inDraft',{
			url:'/indraft',
			templateUrl:'app/modules/selling/views/products.view.html'
		})
		.state('manage.addProduct',{
			url:'/addProduct',
			templateUrl:'app/modules/selling/views/products-add.view.html'
		})
	}
])